### ISSUE TITLE
[feature] Support drop

### ISSUE THREAD

**Issue by Freed-Wu** [lambdalisue/vim-fern#362]
<https://github.com/Shougo/defx.nvim/blob/master/doc/defx.txt#L286>

**Comment by lambdalisue** [comment]
Please write details on this issue.

**Comment by Freed-Wu** [comment]
`drop` means if a file has been opened in a window, just move cursor to the window. If not, open the file by create a new window by some method (e.g. split, edit).

**Comment by mityu** [comment]
It seems this can be closed.
