### ISSUE TITLE
Default branch warning

### ISSUE THREAD

**Issue by ejoubaud** [lambdalisue/vim-fern#489]
I just installed fern using Plug by adding to my vimrc:

```
Plug 'lambdalisue/fern.vim'
```

Then on startup I got the following warning:

```
[fern] The default branch of fern.vim has changed from "master" to "main". Please re-install fern.vim from the latest "main" branch.
[fern] Disable this warning message by adding "let g:fern_disable_startup_warnings = 1" on your vimrc.
```

I was able to fix the issue with:

```
Plug 'lambdalisue/fern.vim', { 'branch': 'main' }
```

(then `rm -rf ~/.vim/plugged/fern.vim` > `vim ` > `:PlugInstall`)

But feels like a less than optimal first install experience. Perhaps this should be documented in the readme?

**Comment by lambdalisue** [comment]
Does plug.vim use master instead of main, even though fern.vim itself uses main as the default branch? Or is this not the first time, and did you have fern.vim under ~/.vim/plugged before fern.vim changed its default branch to main?
