### ISSUE TITLE
Drawer very slow on large trees

### ISSUE THREAD

**Issue by jclsn** [lambdalisue/vim-fern#503]
If you use the drawer on e.g. the Linux kernel source tree, performance gets painfully slow. You are probably aware of this, but is there no way to improve the performance?

**Comment by lambdalisue** [comment]
I'm sorry but I don't have enough information to say something.

**Comment by lambdalisue** [comment]
I have cloned https://github.com/torvalds/linux and opened with fern but I feel it's fast enough.

https://github.com/user-attachments/assets/b1f55199-1a20-4f64-90f2-5e08f114e19a

**Comment by jclsn** [comment]
I just did some research and it seems this is caused by https://github.com/lambdalisue/vim-fern-git-status

After adding the suggested settings for improving performance, the problem disappeared

```
" Disable listing ignored files/directories
let g:fern_git_status#disable_ignored = 1

" Disable listing untracked files
let g:fern_git_status#disable_untracked = 1

" Disable listing status of submodules
let g:fern_git_status#disable_submodules = 1

" Disable listing status of directories
let g:fern_git_status#disable_directories = 1
```
