### ISSUE TITLE
Fern may wrongly overwrites a non-fern buffer.

### ISSUE THREAD

**Issue by mityu** [lambdalisue/vim-fern#514]
**Problem**

Fern wrongly overwrites a new, non-fern buffer in certain situation.

**Reproduce steps**

- Prepare this `repro.vim`

```vim
set nocompatible

" Please modify this path.
set runtimepath^=~/.cache/vim/pack/minpac/opt/vim-fern/

autocmd VimEnter * ++once call timer_start(10, {-> s:repro()})

function s:repro() abort
  Fern /
  split
  enew
endfunction
```

- Run Vim with `vim -u repro.vim`
- The current buffer (bufnr must be 2) has a file tree display although it's a anonymous, non-fern buffer.

**Environment**

- Vim 9.1.842
- Neovim v0.11.0-dev-1108+g5a86360400

**The cause of this bug**

1. At the `split` command at line 2 in `s:repro` function, fern's auto duplication feature will create new fern buffer and trigger asynchronous viewer draws.  At this time, the draws are not done yet and the new buffer is empty.

```
+----------------------------------------+
|  bufnr:2                               |
|  bufname:fern://...                    |
+----------------------------------------+
|  bufnr:1                               |
|  bufname:fern://...                    |
+----------------------------------------+
```

2. `enew` command at line 3 in `s:repro` function opens a new empty buffer.  However, since `enew` reuse the current buffer if it's not modified, the current buffer will be a non-fern buffer with keeping its bufnr same to one that the previously created fern buffer had.

```
+----------------------------------------+
|  bufnr:2                               |
|  bufname:(anonymous)                   |
+----------------------------------------+
|  bufnr:1                               |
|  bufname:fern://...                    |
+----------------------------------------+
```

3. Since the bufnr is same, fern.vim's drawer will draw its contents to current buffer though it's no longer a fern buffer.

```
+----------------------------------------+
|  bufnr:2                               |
|  bufname:(anonymous, wrongly written)  |
+----------------------------------------+
|  bufnr:1                               |
|  bufname:fern://...                    |
+----------------------------------------+
```

(EDIT: Fix buffer positions in figures)

**Comment by mityu** [comment]
Sample screenshot.  Ran on Vim.

<img width="659" alt="image" src="https://github.com/user-attachments/assets/5e0b596f-c131-4e4e-944f-862367f8bc7b">

**Comment by lambdalisue** [comment]
I'll check it after Vimconf. Let me know if I forget about this issue.

**Comment by mityu** [comment]
OK :+1:.

Please don't mind, I don't think this is a critical issue; this rarely happens and we can restore the previous buffer contents with undo ;).

**Comment by mityu** [comment]
@lambdalisue ping

**Comment by lambdalisue** [comment]
I could reproduce the issue but it seems a bit complicated...

**Comment by lambdalisue** [comment]
@mityu Could you try https://github.com/lambdalisue/vim-fern/pull/516?

**Comment by mityu** [comment]
Seems to be working really well :+1:
Thank you.
