### ISSUE TITLE
[Feature request] Allow core mappings to be remappable

### ISSUE THREAD

**Issue by rieje** [lambdalisue/vim-fern#515]
Is there a reason core mappings can't be mapped or is it more of an artificial limitation? `?` occupies the useful default vim mapping to search backwards (useful in a Fern buffer) and `.` is only useful if you use prompt actions (personally I have everything needed on bindings). 

I would like `.` to bind to toggle hidden files since it makes sense mnemonically (both `h` and `H` are useful in a Fern buffer, either as Fern or default Vim binding, so they are already taken). I've used other similar plugins as well as TUI file managers and these are typical default and mnemonic hotkeys for toggling visibility of hidden files. 

It seems like moving core mappings to default mappings has no downsides--users can simply remap them and the defaults would be unchanged. On the plus side, users can maintain consistent and familiar bindings used in similar plugins and external file manager applications.

**Comment by lambdalisue** [comment]
The core mappings are provided by an internal library so it's configured in a bit different path.

You can disable those core mappings by re-mapping it. See https://github.com/lambdalisue/vim-fern/blob/95218a9eeb5bf25ff30196b8700eeb64b8f3aeba/doc/fern.txt#L153-L158

Or use `<Nop>` to completely disable that like

```vim
nnoremap <buffer> <Nop> <Plug>(fern-action-help)
```
